default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: lennon
  password: "@Lennon123"
  host: localhost
  port: 5432


development:
  <<: *default
  database: curso_blog6_development


test:
  <<: *default
  database: curso_blog6_test

production:
  primary: &primary_production
    <<: *default
    database: curso_blog6_production
    username: curso_blog6
    password: <%= ENV["CURSO_BLOG6_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: curso_blog6_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: curso_blog6_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: curso_blog6_production_cable
    migrations_paths: db/cable_migrate
